# Generated by Django 5.2.8 on 2025-11-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='பெயர் (Name)')),
                ('phone', models.CharField(max_length=15, verbose_name='தொலைபேசி எண் (Phone)')),
                ('address', models.TextField(verbose_name='முகவரி (Address)')),
                ('problem', models.TextField(verbose_name='என்ன வேலை? (Work Needed)')),
                ('date', models.DateField(verbose_name='தேதி (Date)')),
                ('time', models.TimeField(verbose_name='நேரம் (Time)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
