# Generated by Django 5.2.1 on 2025-11-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
