# Generated by Django 5.2.8 on 2025-11-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_address_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='completed',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='நிலை / Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.TextField(verbose_name='முகவரி (Address)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='தேதி (Date)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100, verbose_name='பெயர் (Name)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='தொலைபேசி எண் (Phone)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='problem',
            field=models.TextField(verbose_name='என்ன வேலை? (Work Needed)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(verbose_name='நேரம் (Time)'),
        ),
    ]
